#include<stdio.h>
#include<conio.h>
void main()
{
int m1,m2,m3;
clrscr();
	 printf("Enter marks of physics is :\n");
	 scanf("%d",&m1);
	 printf("you have enterned marks of physics is :%d\n",m1);
	 printf("Enter marks of chemistry is :\n");
	 scanf("%d",&m2);
	 printf("you have enterned marks of chemistry is :%d\n",m2);
	 printf("Enter marks of maths is :\n");
	 scanf("%d",&m3);
	 printf("you have enterned marks of maths is :%d\n",m3);
getch();
}